import { createSlice } from '@reduxjs/toolkit'

// Create a slice of the Redux store for treatments
const treatments = createSlice({
  name: 'treatments', // Name of the slice
  initialState: {
    items: [], // Array to store treatment items
    treatmentType: null, // Selected treatment type
    error: null, // Error message
    selectedTreatment: []
  },
  reducers: {
    setItems: (store, action) => {
      store.items = action.payload
    },
    setTreatmentType: (store, action) => {
      store.treatmentType = action.payload // Update the treatmentType with the payload
    },
    setError: (store, action) => {
      store.error = action.payload // Update the error with the payload
    },
    setSelectedTreatment: (store, action) => {
      store.selectedTreatment = action.payload // Update the treatmentType with the payload
    }
  }
})

// Extract the action creators generated by the treatments slice
export const { setItems, setTreatmentType, setError, setSelectedTreatment } = treatments.actions

export default treatments // Export the treatments slice as the default export
