import { createSlice } from '@reduxjs/toolkit'

// Create a slice of the Redux store for user
const user = createSlice({
  name: 'user', // Name of the slice
  initialState: {
    userId: null,
    accessToken: null,
    error: null,
    firstName: null,
    lastName: null,
    mobilePhone: null,
    email: null,
    pickedDate: []
  },
  reducers: {
    setUserId: (store, action) => {
      store.userId = action.payload // Update the userId with the payload
    },
    setFirstName: (store, action) => {
      store.firstName = action.payload // Update the firstName with the payload
    },
    setLastName: (store, action) => {
      store.lastName = action.payload // Update the lastName with the payload
    },
    setMobilePhone: (store, action) => {
      store.mobilePhone = action.payload // Update the mobilePhone with the payload
    },
    setEmail: (store, action) => {
      store.email = action.payload // Update the email with the payload
    },
    setAccessToken: (store, action) => {
      store.accessToken = action.payload // Update the accessToken with the payload
    },
    setError: (store, action) => {
      store.error = action.payload // Update the error with the payload
    },

    loginSuccess: (store, action) => {
      const { accessToken } = action.payload
      store.accessToken = accessToken

      // Store the access token in local storage
      localStorage.setItem('accessToken', accessToken)
    },
    logout: (store) => {
      store.userId = null // Clear the userId
      store.email = null // Clear the email
      store.accessToken = null // Clear the accessToken
      store.pickedDate = null // Clear the pickedDate
      localStorage.removeItem('accessToken') // Remove access token from local storage
    },
    setUserInfo: (store, action) => {
      const { userId, firstName, lastName, mobilePhone, email } = action.payload
      store.userId = userId
      store.firstName = firstName
      store.lastName = lastName
      store.mobilePhone = mobilePhone
      store.email = email
    }
  }
})

// Extract the action creators generated by the user slice
export const {
  setUserId,
  setFirstName,
  setLastName,
  setAccessToken,
  setMobilePhone,
  setEmail,
  setError,
  loginSuccess,
  logout,
  setUserInfo // Add setUserInfo action
} = user.actions

export default user // Export the user slice as the default export
